stages:
  books_to_paragraphs:
    cmd: python albalat/scripts/books_to_paragraphs.py 
      albalat/data/interim/paragraphs.parquet --no-streaming
    outs:
    - albalat/data/interim/paragraphs.parquet
    - albalat/data/interim/metadata_ids.csv
  paragraphs_to_chunks:
    cmd: python albalat/scripts/paragraphs_to_chunks.py 
      albalat/data/interim/paragraphs.parquet 
      albalat/data/processed/chunks.parquet 1500 40
    deps:
    - albalat/data/interim/paragraphs.parquet
    - albalat/scripts/books_to_paragraphs.py
    outs:
    - albalat/data/processed/chunks.parquet
  chunks_to_embeddings:
    cmd: bash albalat/scripts/run_embeddings.sh
    deps:
    - albalat/data/processed/chunks.parquet
    - albalat/scripts/run_embedding.sh
    outs:
    - albalat/data/processed/embeddings/
